Misc fixes for 6.2.2

diff --git a/debian/grass.postinst b/debian/grass.postinst
--- a/debian/grass.postinst
+++ b/debian/grass.postinst
@@ -17,8 +17,8 @@ if fgrep -qsx "$dir" "$ldsoconf"; then
     set -e
     case $fgrep_status in
       0|1) ;; # we don't actually care if any lines matched or not
-      *) die "error reading \"$ldsoconf\"; fgrep exited with status" \
-        "$fgrep_status" ;;
+      *) echo "error reading \"$ldsoconf\"; fgrep exited with status" \
+        "$fgrep_status" && exit 1 ;;
     esac
     set +e
     cmp -s "$ldsoconf.dpkg-tmp" "$ldsoconf"
@@ -27,8 +27,8 @@ if fgrep -qsx "$dir" "$ldsoconf"; then
     case $cmp_status in
       0) rm "$ldsoconf.dpkg-tmp" ;; # files are identical
       1) mv "$ldsoconf.dpkg-tmp" "$ldsoconf" ;; # files differ
-      *) die "error comparing \"$ldsoconf.dpkg-tmp\" to \"$ldsoconf\"; cmp" \
-        "exited with status $cmp_status" ;;
+      *) echo "error comparing \"$ldsoconf.dpkg-tmp\" to \"$ldsoconf\"; cmp" \
+        "exited with status $cmp_status" && exit 2 ;;
     esac
 fi
 
