Changes for ld.so

diff --git a/debian/grass.postinst b/debian/grass.postinst
--- a/debian/grass.postinst
+++ b/debian/grass.postinst
@@ -4,12 +4,32 @@
 
 set -e
 
+# Removes obsolete path in the main ld.so configuration file.
+# This should be removed post-lenny.
 dir="/usr/lib/grass/lib"
 ldsoconf="/etc/ld.so.conf"
-
-# is the line not already present?
-if ! fgrep -qsx "$dir" "$ldsoconf"; then
-  echo "$dir" >> "$ldsoconf"
+# is the line present?
+if fgrep -qsx "$dir" "$ldsoconf"; then
+    # rewrite the file (very carefully)
+    set +e
+    fgrep -svx "$dir" "$ldsoconf" > "$ldsoconf.dpkg-tmp"
+    fgrep_status=$?
+    set -e
+    case $fgrep_status in
+      0|1) ;; # we don't actually care if any lines matched or not
+      *) die "error reading \"$ldsoconf\"; fgrep exited with status" \
+        "$fgrep_status" ;;
+    esac
+    set +e
+    cmp -s "$ldsoconf.dpkg-tmp" "$ldsoconf"
+    cmp_status=$?
+    set -e
+    case $cmp_status in
+      0) rm "$ldsoconf.dpkg-tmp" ;; # files are identical
+      1) mv "$ldsoconf.dpkg-tmp" "$ldsoconf" ;; # files differ
+      *) die "error comparing \"$ldsoconf.dpkg-tmp\" to \"$ldsoconf\"; cmp" \
+        "exited with status $cmp_status" ;;
+    esac
 fi
 
 if [ "$1" = "configure" ]; then
@@ -19,3 +39,5 @@ fi
 #DEBHELPER#
 
 exit 0
+
+
